### ISSUE TITLE
Analytics Integration Phase 2

### ISSUE THREAD

**Issue by tammycamp** [stellar/stellar-client#1075]
We'd like to move into phase 2 of our analytics integration.

In phase 2, we'd like to  track the following event types:

- Stellars received (server side installation)
- Referrals
- Usage

All details can be found in our Google Doc - "Analytics Events - Stellar".

@dirtyanalytics please let me know if I've missed anything.

**Comment by bekkibolthouse** [comment]
Closing this ticket in anticipation of event-specific issues.
