### ISSUE TITLE
Whole client turns grey after login

### ISSUE THREAD

**Issue by EverettForth** [stellar/stellar-client#1115]
My user, onecred.com, with many transactions, is not able to use the stellar client any more.
After logging in, I see the home screen for about 2 seconds, and then everything turns grey.

Previously, after logging in, it seemed like it was using a lot of cpu for a while before showing me transactions.

**Comment by bekkibolthouse** [comment]
The reference implementation client at this time is not designed to support very large transaction history (e.g. enterprise scale); a long tx history will impact its performance, esp when loading.  We may address this in the future.  Building an enterprise client could be a project to be undertaken by a community member, or a business venture.
