### ISSUE TITLE
a(...) is null

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-client#1134]
https://app.getsentry.com/gostellarorg/stellar-client/group/50577440/

----

Interesting note:  this error is being generated on the login page, which doesn't show a recaptcha.

**Comment by nullstyle** [comment]
This appears to be an issue with calling into Recaptcha prior to the document.load event being called.

If you look into recaptcha.html template, we are directly calling the `Recaptcha.*` functions.  It's possible that the user clicked one of those links prior to `document.load` event being triggered.

**Comment by deckar01** [comment]
We do configure reCAPTCHAProvider (the angular wrapper for reCaptcha) in app.js [[1]](https://github.com/stellar/stellar-client/blob/master/app/scripts/app.js#L47), which would probably fail if the underlying reCaptcha script hasn't loaded. The module loads the original reCaptcha script dynamically [[2]](https://github.com/mllrsohn/angular-re-captcha/blob/master/angular-re-captcha.js#L14).

[1] https://github.com/stellar/stellar-client/blob/master/app/scripts/app.js#L47
[2] https://github.com/mllrsohn/angular-re-captcha/blob/master/angular-re-captcha.js#L14

**Comment by nullstyle** [comment]
I was just able to repro this.  The error (and a few other similar errors) occur when angular destroys the scope and elements underneath a scope prior to `Recaptcha.create` finishes.  Recpatcha assumes the element you tell it to render within will be there.

There’s not an easy way to solve this specific error, other than doing something IMO bad like:

1.  Prevent navigation until the recaptcha loads
2.  Render recaptcha into an element that will be guaranteed to be present (such as in the footer) and then use CSS to position it on the form correctly.

Neither of these are worth the trouble, IMO, for a bug that doesn’t affect the user experience.  I’m going to simply ignore the error in our sentry configs.
