### ISSUE TITLE
Cannot read property 'to_human_full' of null

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-client#1153]
https://app.getsentry.com/gostellarorg/stellar-client/group/35926343/

----

It appears that there are instances that $scope.send is reset after a transaction has succeeded, but before the analytics events have been triggered.

**Comment by bartekn** [comment]
I think I know when it's happening. When impatient user is waiting for a transaction confirmation but it takes a bit longer (like 10 seconds), he/she can close a send pane and open it again to repeat a process. This does not cancel a previously sent transaction but `amount` object is set to `null`. After a transaction is successfully sent and we're trying to track an event, `$scope.send.amount` variable is `null` what causes this error.
