### ISSUE TITLE
Add a flash message to notify users the limited capabilities available

### ISSUE THREAD

**Issue by irisli** [stellar/stellar-client#1201]
awaiting copy from @jessica-collier

**Comment by jessica-collier** [comment]
Title: The Stellar network has upgraded!
Body: If you've already upgraded, view your lumens balance with the (account viewer)[https://www.stellar.org/account-viewer/#/]. To upgrade, or to see what you still have in addition to lumens, log in below.

**Comment by irisli** [comment]
Done in: https://github.com/stellar/stellar-client/pull/1202
