### ISSUE TITLE
Abandon the account move funds to a new one

### ISSUE THREAD

**Issue by skironDotNet** [stellar/stellar-client#1205]
I was playin around with stellar and by mistake pasted the private key to the browser.
I assuming my account to be compromised now, I want to obrain a new private key (new account) but would be nice to have a way to transfer the remaining 20 to a new account and then deactivate old account.

I think it may be alreay implemented somehow based on other users feedback, but I'm using windows client and in browser client and can't find such option.
Also assuming the fee is 0.00001 the account balance would have to be minimum 20.00001 or more to move all funds to a new account.

Please advise. Thanks!

**Comment by bartekn** [comment]
You need [`account_merge` operation](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#account-merge) which moves remaining XLM funds to the other account. You can try to build a transaction using [Laboratory](https://www.stellar.org/laboratory/) or ask for help in our slack or reddit.

**Comment by skironDotNet** [comment]
I tried via Laboratory. I'm getting
"title": "Transaction Failed",
  "status": 400,
    "result_codes": {
      "transaction": "tx_bad_auth_extra"
    },

I put old address as source account, obtained Transaction Sequence Number via Fetch... button, then fee 100, Memo: none, Time bonds: empty, 
Operation Type: Account Merge
Desitnation: my new and activated account public address with balance 25
Source:  my old and activated account public address with balance over 20

Went to transaction signer, and signed by both private keys from old and new account.
Not sure what am I doing wrong.

**Comment by bartekn** [comment]
Have you change the network to public (top right switch)?

**Comment by skironDotNet** [comment]
Yes (in test mode it would not fetch TSN obiously), but I think 90% was the fee fault, because at first when I tried (well done multiple tries) with explicit fee it faild, and my balance became 20 (I had 20.00001 before) then next try without fee "no blance" so sent 1 XLM to old account, then tried again, error was "account inactive" so sent 25 to new account. And finally now just after my comment I removed fee (left field empty) and removed signature from new account (not sure if it mattered but used only one signature from old account) and it worked.

Thanks a lot it was a great experience with Stellar Laboratory. As a side comment. I'm surprised this operation is not part of Stellar Wallet
